version: '3'

services:
  backend:
    container_name: flask
    build: ./backend
    command: python run.py
    volumes: 
      - .:/home/app
    ports:
      - "5000:5000"
    depends_on: 
      - mysqldb
    networks:
      - mysql-compose-network
  
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
    volumes:
      - mysql-flask-book:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

volumes: 
  mysql-flask-book:
      external: true